# PRESENTATION NOTE: This file is commented to make the project easier to explain during the final committee presentation.
"""Phase 3: supply chain events and shipments

Revision ID: 5cb96f604c18
Revises: acc45f0de156
Create Date: 2026-08-12 05:10:36.492547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb96f604c18'
down_revision = 'acc45f0de156'
branch_labels = None
depends_on = None


# What this code does: Applies this database migration by creating or changing the required database structures.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('from_org_id', sa.Integer(), nullable=True),
    sa.Column('to_org_id', sa.Integer(), nullable=True),
    sa.Column('tracking_no', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['from_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['to_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_chain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


# What this code does: Reverses this database migration to return the schema to the previous version.
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_chain_events')
    op.drop_table('shipments')
    # ### end Alembic commands ###
